import { useEffect } from 'react'
import { Link } from 'react-router-dom'

const SECTIONS = [
  {
    heading: 'What Noor is',
    body: 'Noor is a fictional fintech company created as part of a software portfolio project. It is not a licensed financial institution, it holds no accounts or funds, and nothing on this site is a real financial product, licence, or offer. References to regulation, licensing, and payment schemes are part of the fiction.',
  },
  {
    heading: 'What happens to your chat messages',
    body: 'The Kafi chat assistant is a working demo. Messages you type are sent to our demo server and processed by Google’s Gemini API to generate a reply. They are not saved to a database by this project, but they do transit third-party infrastructure (Google, and our hosting providers) which may retain standard request logs. Please do not enter real personal or financial details — no CNIC numbers, account numbers, phone numbers, or passwords. The demo never needs them, and no real support agent will read them.',
  },
  {
    heading: 'Accounts, cookies, and tracking',
    body: 'This site has no sign-up, no user accounts, no advertising, and sets no tracking cookies. Our hosting providers may collect basic, anonymous request logs (such as IP address and pages visited) as part of operating their platforms.',
  },
  {
    heading: 'Terms of use',
    id: 'terms',
    body: 'This site is provided as-is, for demonstration purposes only. Noor is fictional; nothing here constitutes a real service, offer, or advice of any kind. Replies from the Kafi assistant are generated by a language model against a synthetic FAQ dataset and describe fictional policies — do not rely on them for anything. The RedPen, Lumen, and Prism tools linked from this site are real open-source portfolio projects with their own repositories.',
  },
]

export default function Privacy() {
  useEffect(() => {
    const target = window.location.hash && document.querySelector(window.location.hash)
    if (target) {
      target.scrollIntoView()
    } else {
      window.scrollTo(0, 0)
    }
  }, [])

  return (
    <div className="min-h-screen bg-emerald-950 font-sans">
      <header className="border-b border-emerald-800/60">
        <div className="mx-auto flex max-w-2xl items-center justify-between px-5 py-4">
          <Link to="/" viewTransition className="flex items-center gap-2.5">
            <img src="/noor.svg" alt="" className="h-8 w-8" />
            <span className="font-semibold tracking-tight text-white">Noor</span>
          </Link>
          <Link
            to="/"
            viewTransition
            className="text-sm text-emerald-100/60 transition hover:text-gold-300"
          >
            Back to home
          </Link>
        </div>
      </header>
      <main className="mx-auto max-w-2xl px-5 py-14">
        <h1 className="text-3xl font-semibold tracking-tight text-white">
          Privacy &amp; Terms
        </h1>
        <p className="mt-3 text-sm text-emerald-100/50">
          Last updated July 2026 &middot; Plain language, because it genuinely is simple.
        </p>
        <div className="mt-10 space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.heading} id={s.id}>
              <h2 className="text-lg font-semibold text-gold-300">{s.heading}</h2>
              <p className="mt-3 text-justify text-sm leading-relaxed text-emerald-100/70">
                {s.body}
              </p>
            </section>
          ))}
        </div>
        <p className="mt-14 border-t border-emerald-800/60 pt-6 text-xs leading-relaxed text-emerald-100/40">
          Questions about the project itself? It lives on{' '}
          <a
            href="https://github.com/hnprivv"
            target="_blank"
            rel="noreferrer"
            className="underline decoration-emerald-700 underline-offset-2 transition hover:text-gold-300"
          >
            GitHub
          </a>
          .
        </p>
      </main>
    </div>
  )
}
